// Ambient types for static asset imports (import img from "./foo.jpg").
//
// Next writes these references into next-env.d.ts, but that file is gitignored
// and only (re)generated by `next dev` / `next build`. Our build script runs
// `tsc --noEmit` BEFORE `next build` (see package.json), so on a clean CI
// checkout next-env.d.ts doesn't exist yet and tsc can't resolve *.jpg imports.
// Committing the reference here fixes CI without un-ignoring Next's managed file.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
